### ISSUE TITLE
General >> Plan de proyecto | Roadmap 

### ISSUE THREAD

**Issue by KoolTheba** [OSWeekends/arte-interactivo#8]
Construir desde cero el plan de proyecto flexible y roadmap para volcarlo en Issues y projects ✅
 
- [ ] Definir objetivos a medio y largo plazo (MVP, exposiciones...), dirección/visión de hacia dónde va el proyecto, qué nos planteamos construir y mostrar primero,  etc
- [ ] Research
- [ ] Roadmap desarrollo y proyecto hasta el 1er MVP (timeline, issues...)
    - [ ] Milestones 
    - [ ] Entregas, Demo time
- [ ] Diseño prototipo 
- [ ] Construcción prototipo
- [ ] Recursos necesarios y disponibles 
    - [ ] Repos en GitHub, 
    - [ ] Web propia (dominio+cloud), 
    - [ ] Hardware, 
    - [ ] Espacio desarrollo - Hacker Space, 
    - [ ] Espacio exposición, 
    - [ ] Posible financiación/€€€€
- [ ] Video-documentación y apoyo visual del proyecto
- [ ] Participantes: disponibilidad/perfiles/motivación (mirar issue #2 )
- [ ] Exposición/es: física y/o virtual 
    - [ ] Recorrido, items...
    - [ ] Contenidos explicativos
    - [ ] Documentación, planteamiento para presentar
    - [ ] Dónde lo queremos presentar?
    - [ ] Contactos que nos puedan ayudar 
- [ ] MKT (??)
    - [ ] Comunicación
    - [ ] RRSS 
    - [ ] Contenidos, campañas
    - [ ] Branding, logos, naming 
- [ ] Licenciar el proyecto y re-utilización 
- [ ] Patrocinios, sponsorización
- [ ] Continuidad del proyecto: mantenimiento, fases posteriores...
